### ISSUE TITLE
How to modify  train_arm.py file if I want to retrain  the movement of the robotic arm ?

### ISSUE THREAD

**Issue by TONG369** [zuoym15/craves.ai#7]
Hello，

If I redefine the movement of the robotic arm while moving, and to retrain. Which files should I modify? Thank you~

I am looking forward to your reply.

**Comment by zuoym15** [comment]
Sorry, I’m afraid I don’t follow you. Could you please explain more clearly what do you want to modify? 
Thanks!

**Comment by TONG369** [comment]
I think about it again, when I have a new idea, leave a message. Thank you! ! !

**Comment by TONG369** [comment]
I think about it again, when I have a new idea, leave a message. Thank you! ! !

**Comment by TONG369** [comment]
I think about it again, when I have a new idea, leave a message. Thank you! ! !
